name = "icctutor-link"
compatibility_date = "2024-01-01"

pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "icctutor-db"
database_id = "9af27145-a8cd-48ae-b050-4544a15a9978"

node_compat = true